name: Health check

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://pokelol.herokuapp.com
