name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master, combine-jobs]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      # - name: e2e tests
      #  uses: cypress-io/github-action@v4
      #  with:
      #    start: npm run start-prod
      #    wait-on: http://localhost:5000
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokelol"
          heroku_email: "yessergire.mohamed@outlook.com"
          healthcheck: "https://pokelol.herokuapp.com/health"
          checkstring: "ok"
          delay: 90
          rollbackonhealthcheckfailed: true

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: print commit data
        env:
          COMMIT_DATA: ${{ toJson(github.event.commits) }}
        run: echo "$COMMIT_DATA"
      - name: print commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Bump version and push tag
        if: ${{ () && (github.event_name == 'push') }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
